from collections import OrderedDict

WORKSHEET_COLUMNS = [
    'date',
    'time_of_day',
    'primary_type',
    'description',
    'location_description', 
    'iucr',
    'case_number',
    'block',
    'ward',
    'community_area',
    'beat',
    'district',
]

COMM_AREA = {
    "08" : "Near North Side",
    "32": "Loop",
    "33": "Near South Side",
    "05": "North Center",
    "06": "Lake View",
    "07": "Lincoln Park",
    "21": "Avondale",
    "22": "Logan Square",
    "01": "Rogers Park",
    "02": "West Ridge",
    "03": "Uptown",
    "04": "Lincoln Square",
    "09": "Edison Park",
    "10": "Norwood Park",
    "11": "Jefferson Park",
    "12": "Forest Glen",
    "13": "North Park",
    "14": "Albany Park",
    "76": "O'Hare",
    "77": "Edgewater",
    "15": "Portage Park",
    "16": "Irving Park",
    "17": "Dunning",
    "18": "Montclare",
    "19": "Belmont Cragin",
    "20": "Hermosa",
    "23": "Humboldt Park",
    "24": "West Town",
    "25": "Austin",
    "26": "West Garfield Park",
    "27": "East Garfield Park",
    "28": "Near West Side",
    "29": "North Lawndale",
    "30": "South Lawndale",
    "31": "Lower West Side",
    "34": "Armour Square",
    "35": "Douglas",
    "36": "Oakland",
    "37": "Fuller Park",
    "38": "Grand Boulevard",
    "39": "Kenwood",
    "40": "Washington Park",
    "41": "Hyde Park",
    "42": "Woodlawn",
    "43": "South Shore",
    "60": "Bridgeport",
    "69": "Greater Grand Crossing",
    "56": "Garfield Ridge",
    "57": "Archer Heights",
    "58": "Brighton Park",
    "59": "McKinley Park",
    "61": "New City",
    "62": "West Elsdon",
    "63": "Gage Park",
    "64": "Clearing",
    "65": "West Lawn",
    "66": "Chicago Lawn",
    "67": "West Englewood",
    "68": "Englewood",
    "44": "Chatham",
    "45": "Avalon Park",
    "46": "South Chicago",
    "47": "Burnside",
    "48": "Calumet Heights",
    "49": "Roseland",
    "50": "Pullman",
    "51": "South Deering",
    "52": "East Side",
    "53": "West Pullman",
    "54": "Riverdale",
    "55": "Hegewisch",
    "70": "Ashburn",
    "71": "Auburn Gresham",
    "72": "Beverly",
    "73": "Washington Heights",
    "74": "Mount Greenwood",
    "75": "Morgan Park",
}

TYPE_GROUPS = OrderedDict([
    ('common_locations', [
        'STREET',
        'RESIDENCE',
        'SIDEWALK',
        'APARTMENT',
        'PARKING LOT/GARAGE(NON.RESID.)',
        'ALLEY',
    ]),
    ('airport', [
        'AIRPORT/AIRCRAFT', 
        'AIRPORT TERMINAL UPPER LEVEL - SECURE AREA',
        'AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA',
        'AIRPORT EXTERIOR - NON-SECURE AREA',
        'AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA',
        'AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA',
        'AIRPORT PARKING LOT',
        'AIRPORT TERMINAL LOWER LEVEL - SECURE AREA',
        'AIRPORT VENDING ESTABLISHMENT',
        'AIRCRAFT',
        'AIRPORT BUILDING NON-TERMINAL - SECURE AREA',
        'AIRPORT EXTERIOR - SECURE AREA',
        'AIRPORT TRANSPORTATION SYSTEM (ATS)',
        'AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA',
    ]),
    ('business_banking', [
        'BANK',
        'CURRENCY EXCHANGE',
        'ATM (AUTOMATIC TELLER MACHINE)',
        'CREDIT UNION',
        'SAVINGS AND LOAN',
    ]),
    ('business_eatery', [
        'RESTAURANT',
        'BANQUET HALL',
    ]),
    ('business_hotel_motel', [
        'HOTEL/MOTEL',
        'HOTEL',
        'MOTEL',
        'ROOMING HOUSE',
    ]),
    ('business_liquor', [
        'BAR OR TAVERN',
        'TAVERN/LIQUOR STORE',
        'TAVERN',
        'CLUB',
        'LIQUOR STORE',
    ]),
    ('business_office', [
        'COMMERCIAL / BUSINESS OFFICE',
        'CONSTRUCTION SITE',
        'WAREHOUSE',
        'FACTORY/MANUFACTURING BUILDING',
        'MEDICAL/DENTAL OFFICE',
        'ANIMAL HOSPITAL',
        'OFFICE',
        'FACTORY',
        'LIVERY STAND OFFICE',
        'LOADING DOCK',
        'JUNK YARD/GARBAGE DUMP',
        'LIVERY AUTO',
        'TRUCKING TERMINAL',
    ]),
    ('business_retail', [
        'SMALL RETAIL STORE',
        'GROCERY FOOD STORE',
        'DEPARTMENT STORE',
        'GAS STATION',
        'DRUG STORE',
        'CONVENIENCE STORE',
        'BARBERSHOP',
        'ATHLETIC CLUB',
        'SPORTS ARENA/STADIUM',
        'CAR WASH',
        'MOVIE HOUSE/THEATER',
        'APPLIANCE STORE',
        'COIN OPERATED MACHINE',
        'POOL ROOM',
        'BOWLING ALLEY',
        'PAWN SHOP',
        'NEWSSTAND',
        'RETAIL STORE',
        'GAS STATION DRIVE/PROP.',
        'GARAGE/AUTO REPAIR',
        'BARBER SHOP/BEAUTY SALON',
        'LAUNDRY ROOM',
        'CLEANING STORE',
    ]),
    ('cha', [
        'CHA PARKING LOT/GROUNDS',
        'CHA APARTMENT',
        'CHA HALLWAY/STAIRWELL/ELEVATOR',
        'CHA GROUNDS',
        'CHA HALLWAY',
        'CHA PARKING LOT',
        'CHA STAIRWELL',
        'CHA LOBBY',
        'CHA BREEZEWAY',
        'CHA PLAY LOT',
        'CHA ELEVATOR',
    ]),
    ('cta', [
        'CTA PLATFORM',
        'CTA BUS',
        'CTA TRAIN',
        'CTA GARAGE / OTHER PROPERTY',
        'CTA BUS STOP',
        'CTA  L  PLATFORM',
        'CTA PROPERTY',
        'CTA  L  TRAIN',
    ]),
    ('gov', [
        'POLICE FACILITY/VEH PARKING LOT',
        'GOVERNMENT BUILDING/PROPERTY',
        'FIRE STATION',
        'JAIL / LOCK-UP FACILITY',
        'FEDERAL BUILDING',
        'COUNTY JAIL',
    ]),
    ('hospital', [
        'HOSPITAL BUILDING/GROUNDS',
        'NURSING HOME/RETIREMENT HOME',
        'HOSPITAL',
        'NURSING HOME',
    ]),
    ('library', ['LIBRARY']),
    ('indoors_residence', [
        'RESIDENCE PORCH/HALLWAY',
        'HOUSE',
        'PORCH',
        'HALLWAY',
        'GARAGE',
        'BASEMENT',
        'VESTIBULE',
        'COACH HOUSE',
        'STAIRWELL'
    ]),
    ('other', ['OTHER']),
    ('outdoors_public', [
        'RIVER',
        'ALLEY',
        'PARK PROPERTY',
        'HIGHWAY/EXPRESSWAY',
        'LAKEFRONT/WATERFRONT/RIVERBANK',
        'FOREST PRESERVE',
        'BRIDGE',
        'PARKING LOT',
        'DUMPSTER',
        'WOODED AREA',
        'LAKE',
        'SEWER',
        'PRAIRIE',
        'RIVER BANK',
        'GANGWAY',
    ]),
    ('outdoors_residence', [
        'RESIDENCE-GARAGE',
        'RESIDENTIAL YARD (FRONT/BACK)',
        'DRIVEWAY - RESIDENTIAL',
        'YARD',
        'DRIVEWAY',
    ]),
    ('worship', [
        'CHURCH/SYNAGOGUE/PLACE OF WORSHIP',
        'CEMETARY',
        'CHURCH',
        'CHURCH PROPERTY',
        'FUNERAL PARLOR',
    ]),
    ('school', [
        'SCHOOL, PUBLIC, BUILDING',
        'SCHOOL, PUBLIC, GROUNDS',
        'SCHOOL, PRIVATE, BUILDING',
        'COLLEGE/UNIVERSITY GROUNDS',
        'SCHOOL, PRIVATE, GROUNDS',
        'DAY CARE CENTER',
        'COLLEGE/UNIVERSITY RESIDENCE HALL',
        'SCHOOL YARD',
        'PUBLIC HIGH SCHOOL',
        'YMCA',
        'PUBLIC GRAMMAR SCHOOL',
    ]),
    ('transportation', [
        'OTHER RAILROAD PROP / TRAIN DEPOT',
        'OTHER COMMERCIAL TRANSPORTATION',
        'RAILROAD PROPERTY',
    ]),
    ('vacant', [
        'VACANT LOT',
        'VACANT LOT/LAND',
        'ABANDONED BUILDING',
    ]),
    ('vehicle', [
        'VEHICLE NON-COMMERCIAL',
        'TAXICAB',
        'VEHICLE-COMMERCIAL',
        'DELIVERY TRUCK',
        'AUTO',
        'BOAT/WATERCRAFT',
        'TRUCK',
        'TAXI CAB',
        'TRAILER',
    ]),
])

