WORKSHEET_COLUMNS = [
    'orig_date',
    'time_of_day',
    'primary_type',
    'description',
    'location_description', 
    'iucr',
    'case_number',
    'block',
    'ward',
    'community_area',
    'beat',
    'district',
]

TYPE_GROUPS = {
    'airport': [
        'AIRPORT/AIRCRAFT', 
        'AIRPORT TERMINAL UPPER LEVEL - SECURE AREA',
        'AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA',
        'AIRPORT EXTERIOR - NON-SECURE AREA',
        'AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA',
        'AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA',
        'AIRPORT PARKING LOT',
        'AIRPORT TERMINAL LOWER LEVEL - SECURE AREA',
        'AIRPORT VENDING ESTABLISHMENT',
        'AIRCRAFT',
        'AIRPORT BUILDING NON-TERMINAL - SECURE AREA',
        'AIRPORT EXTERIOR - SECURE AREA',
        'AIRPORT TRANSPORTATION SYSTEM (ATS)',
        'AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA',
    ],
    'business_banking': [
        'BANK',
        'CURRENCY EXCHANGE',
        'ATM (AUTOMATIC TELLER MACHINE)',
        'CREDIT UNION',
        'SAVINGS AND LOAN',
    ],
    'business_eatery': [
        'RESTAURANT',
        'BANQUET HALL',
    ],
    'business_hotel_motel': [
        'HOTEL/MOTEL',
        'HOTEL',
        'MOTEL',
        'ROOMING HOUSE',
    ],
    'business_liquor': [
        'BAR OR TAVERN',
        'TAVERN/LIQUOR STORE',
        'TAVERN',
        'CLUB',
        'LIQUOR STORE',
    ],
    'business_office': [
        'COMMERCIAL / BUSINESS OFFICE',
        'CONSTRUCTION SITE',
        'WAREHOUSE',
        'FACTORY/MANUFACTURING BUILDING',
        'MEDICAL/DENTAL OFFICE',
        'ANIMAL HOSPITAL',
        'OFFICE',
        'FACTORY',
        'LIVERY STAND OFFICE',
        'LOADING DOCK',
        'JUNK YARD/GARBAGE DUMP',
        'LIVERY AUTO',
        'TRUCKING TERMINAL',
    ],
    'business_retail': [
        'SMALL RETAIL STORE',
        'GROCERY FOOD STORE',
        'DEPARTMENT STORE',
        'GAS STATION',
        'DRUG STORE',
        'CONVENIENCE STORE',
        'BARBERSHOP',
        'ATHLETIC CLUB',
        'SPORTS ARENA/STADIUM',
        'CAR WASH',
        'MOVIE HOUSE/THEATER',
        'APPLIANCE STORE',
        'COIN OPERATED MACHINE',
        'POOL ROOM',
        'BOWLING ALLEY',
        'PAWN SHOP',
        'NEWSSTAND',
        'RETAIL STORE',
        'GAS STATION DRIVE/PROP.',
        'GARAGE/AUTO REPAIR',
        'BARBER SHOP/BEAUTY SALON',
        'LAUNDRY ROOM',
        'CLEANING STORE',
    ],
    'cha': [
        'CHA PARKING LOT/GROUNDS',
        'CHA APARTMENT',
        'CHA HALLWAY/STAIRWELL/ELEVATOR',
        'CHA GROUNDS',
        'CHA HALLWAY',
        'CHA PARKING LOT',
        'CHA STAIRWELL',
        'CHA LOBBY',
        'CHA BREEZEWAY',
        'CHA PLAY LOT',
        'CHA ELEVATOR',
    ],
    'cta': [
        'CTA PLATFORM',
        'CTA BUS',
        'CTA TRAIN',
        'CTA GARAGE / OTHER PROPERTY',
        'CTA BUS STOP',
        'CTA  L  PLATFORM',
        'CTA PROPERTY',
        'CTA  L  TRAIN',
    ],
    'gov': [
        'POLICE FACILITY/VEH PARKING LOT',
        'GOVERNMENT BUILDING/PROPERTY',
        'FIRE STATION',
        'JAIL / LOCK-UP FACILITY',
        'FEDERAL BUILDING',
        'COUNTY JAIL',
    ],
    'hospital': [
        'HOSPITAL BUILDING/GROUNDS',
        'NURSING HOME/RETIREMENT HOME',
        'HOSPITAL',
        'NURSING HOME',
    ],
    'library': ['LIBRARY'],
    'indoors_residence': [
        'RESIDENCE',
        'APARTMENT',
        'RESIDENCE PORCH/HALLWAY',
        'HOUSE',
        'PORCH',
        'HALLWAY',
        'GARAGE',
        'BASEMENT',
        'VESTIBULE',
        'COACH HOUSE',
        'STAIRWELL'
    ],
    'other': ['OTHER'],
    'outdoors_public': [
        'RIVER',
        'STREET',
        'SIDEWALK',
        'PARKING LOT/GARAGE(NON.RESID.)',
        'ALLEY',
        'PARK PROPERTY',
        'HIGHWAY/EXPRESSWAY',
        'LAKEFRONT/WATERFRONT/RIVERBANK',
        'FOREST PRESERVE',
        'BRIDGE',
        'PARKING LOT',
        'DUMPSTER',
        'WOODED AREA',
        'LAKE',
        'SEWER',
        'PRAIRIE',
        'RIVER BANK',
        'GANGWAY',
    ],
    'outdoors_residence': [
        'RESIDENCE-GARAGE',
        'RESIDENTIAL YARD (FRONT/BACK)',
        'DRIVEWAY - RESIDENTIAL',
        'YARD',
        'DRIVEWAY',
    ],
    'worship': [
        'CHURCH/SYNAGOGUE/PLACE OF WORSHIP',
        'CEMETARY',
        'CHURCH',
        'CHURCH PROPERTY',
        'FUNERAL PARLOR',
    ],
    'school': [
        'SCHOOL, PUBLIC, BUILDING',
        'SCHOOL, PUBLIC, GROUNDS',
        'SCHOOL, PRIVATE, BUILDING',
        'COLLEGE/UNIVERSITY GROUNDS',
        'SCHOOL, PRIVATE, GROUNDS',
        'DAY CARE CENTER',
        'COLLEGE/UNIVERSITY RESIDENCE HALL',
        'SCHOOL YARD',
        'PUBLIC HIGH SCHOOL',
        'YMCA',
        'PUBLIC GRAMMAR SCHOOL',
    ],
    'transportation': [
        'OTHER RAILROAD PROP / TRAIN DEPOT',
        'OTHER COMMERCIAL TRANSPORTATION',
        'RAILROAD PROPERTY',
    ],
    'vacant': [
        'VACANT LOT',
        'VACANT LOT/LAND',
        'ABANDONED BUILDING',
    ],
    'vehicle': [
        'VEHICLE NON-COMMERCIAL',
        'TAXICAB',
        'VEHICLE-COMMERCIAL',
        'DELIVERY TRUCK',
        'AUTO',
        'BOAT/WATERCRAFT',
        'TRUCK',
        'TAXI CAB',
        'TRAILER',
    ],
}

